### ISSUE TITLE
Move the byte slicing/shifting/masking/etc to a utils class

### ISSUE THREAD

**Issue by mmschaefer** [battjt/j1939-84#101]
Move all byte handling of messaging to a utils class.

**Comment by battjt** [comment]
I'm not a big fan of hiding it.  I do think we should have methods on Packet that make it easy to extract data, but abstracting bit manipulation just hides it.  I did add a getPgn(), and am more aware to use getDestination().

**Comment by mmschaefer** [comment]
This work was re-designed to and handled under #244.  This ticket is being closed as it is no longer necessary.
