### ISSUE TITLE
Some FAILs and WARNs should only be listed once.

### ISSUE THREAD

**Issue by battjt** [battjt/j1939-84#149]
Eric says "Failure criteria need not always be evaluated twice; usuallyevaluation with the first response issufficient,and a string compare alone suffices for criterion"

**Comment by gumbelmj** [comment]
Part1 Step 14 is one such place

**Comment by gumbelmj** [comment]
Completed with Recent changes.  If there are still issues we need to create a new issue with the specific problem.
