### ISSUE TITLE
Fix loopback simulator and json files that crash when loading

### ISSUE THREAD

**Issue by mmschaefer** [battjt/j1939-84#164]
Investigate and fix bug causing a crash in the loopback simulator, SIM:_1_MY2020_2.asc.json and SIM:_1_MY2020_3.asc.json when loading configuration

**Comment by gumbelmj** [comment]
Just delete them now

**Comment by mmschaefer** [comment]
JSON files are being abandoned and will not be fixed or updated.  Only the Simulated engine will be maintained going forward.
