### ISSUE TITLE
Add blank line before "Global Component Identification Request" in 6.1.9

### ISSUE THREAD

**Issue by battjt** [battjt/j1939-84#184]

**Comment by mmschaefer** [comment]
![Screen Shot 2020-10-30 at 11 41 03 AM](https://user-images.githubusercontent.com/7682306/97725794-f1493e80-1aa4-11eb-834b-1ba586f19fc5.png)

[check5.j1939-84.txt](https://github.com/battjt/j1939-84/files/5466114/check5.j1939-84.txt)
