### ISSUE TITLE
A5 verification engine hours

### ISSUE THREAD

**Issue by battjt** [battjt/j1939-84#185]
FAIL: 6.1.10.3.b - Fail if any diagnostic information in any ECU is not reset or starts out with unexpected values. /* engine hours is not on the list with for example time since engine start */

Simulation showed a failure, that isn't in the code.  Verify what is going on.  This may have already been fixed.

**Comment by battjt** [comment]
The FAIL is prior to the engine hours test.  The reporting is misleading.

**Comment by gumbelmj** [comment]
#223 and #203 made changes to remove the checking of Diagnostic Information from Part 1 Step 10 per Eric's request:

In the document "CommentsForJoe":

"/* The content in blue is excess. DM28, 20, 33 are not DM11 */"

We need clarification on how and when diagnostic information is to be checked.

**Comment by gumbelmj** [comment]
Eric needs to Strike 6.1.10.2.b from the Spec.

**Comment by ericthomasswenson** [comment]
The better issue to track the document change is believed to be #445

**Comment by gumbelmj** [comment]
This issue will be tracked with #445

**Comment by gumbelmj** [comment]
This issue will be tracked with #445
