### ISSUE TITLE
DM24 should list data stream and Scaled Test Results.

### ISSUE THREAD

**Issue by battjt** [battjt/j1939-84#42]
Data stream information is missing.

**Comment by mmschaefer** [comment]
Update the toString method to include all dataStreams.

**Comment by battjt** [comment]
The requirements are:

> c. Create vehicle list of supported SPNs for data stream.
> d. Create ECU specific list of supported SPNs for test results.
> e. Create ECU specific list of supported freeze frame SPNs.

but in the output I only see 

> (Supporting Test Results)

J1939-73 describe DM24 as a list of SPNs with flags for "scaled test result" and "data stream" and "expanded freeze frame":
>Byte: 3 ...
>  bits 3 Supported in Scaled Test Results See 5.7.24.4
>  bits 2 Supported in Data Stream See 5.7.24.3
>  bits 1 Supported in Expanded Freeze Frame See 5.7.24.2

**Comment by battjt** [comment]
1. This broke OBDTestsModuleTest.
2. I think we want to be more like the old test with each SPN listed with its capabilities.  The old report did fail to make columns, so it is difficult at a glance to see what is what.  For reference:
>    Received SPN 190   - supports freeze frame - supports data stream
>    Received SPN 157   - supports freeze frame - supports scaled results - supports data stream
