### ISSUE TITLE
Part 1 Step 13 reporting of DTC Count failures

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#420]
```
10:31:46.1624 Global DM5 Request
10:31:45.9580 18EAFFF9 CE FE 00 (TX)
10:31:45.9640 18FECE55 FF FF 14 00 00 00 00 00
DM5 from Diesel Particulate Filter Controller (85): OBD Compliance: HD OBD (20), Active Codes: not available, Previously Active Codes: not available
10:31:45.9655 18FECE00 00 00 14 37 E0 1E E0 1E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
10:31:45.9665 18FECE03 00 00 05 00 00 00 00 00
DM5 from Transmission #1 (3): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0
10:31:45.9695 18FECE05 00 01 00 00 00 00 00 00
DM5 from Shift Console - Primary (5): OBD Compliance: Reserved for SAE/Unknown (0), Active Codes: 0, Previously Active Codes: 1
10:31:46.0045 18FECEA7 00 01 FF 00 00 00 00 00
DM5 from Instrument Cluster #2 (167): OBD Compliance: Not available (255), Active Codes: 0, Previously Active Codes: 1
FAIL: 6.1.13.2.a Fail/warn per section A.6, Criteria for Readiness 1 Evaluation
FAIL: 6.1.13.2.b - Fail if any OBD ECU reports active/previously active fault DTCs count not = 0/0
  Reported active fault count = -1
  Reported previously active fault count = -1
```

Comment from Eric:

> Here SA 0 reports all the DM1 and DM2 faults … unsupported fault counts by a distributed component are not a failure as SA 0 provides the counts … SA 85 cannot NACK DM5 because of the OBD Compliance SPN that it must support. 
> 6.1.13.2.b would be better phrased as – 
> i. Fail if no OBD ECU reports active/previously active faults = 0/0
> ii Fail if any OBD ECU provides a DM1 or DM2 fault count greater than 0 for either DM1 or DM2.

**Comment by gumbelmj** [comment]
Eric needs to update Part 1 Step 13 to indicate that N/A shouldn't be considered a failure.

**Comment by ericthomasswenson** [comment]
Current text
_6.1.13.2 Fail/warn criteria: 
a. Fail/warn per section A.6, Criteria for Readiness 1 Evaluation.  
b. Fail if any OBD ECU reports active/previously active fault DTCs count not = 0/0.   
c. Fail if no OBD ECU provides DM5 with readiness bits showing monitor support. 
d. Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU._   

_b. Fail if **no** OBD ECU reports active/previously active fault DTCs **count = 0/0**._   

Still seems the most concise answer ... does it represent the present implementation well?

**Comment by gumbelmj** [comment]
The present implementation will ignore 0xFF but it can be changed to ensure at least one OBD ECU has 0/0 DTC counts.

**Comment by ericthomasswenson** [comment]
The 3.0.0 text for 6.1.13.2 shall be updated to say

_b. Fail if **no** OBD ECU reports active/previously active fault DTCs count **= 0/0**._

This cannot be checked until after the DM11 query (command), and is therefore not checked in 6.1.3.

**Comment by ericthomasswenson** [comment]
as now shown on page 25

b.	Fail if no OBD ECU reports active/previously active fault DTCs count = 0/0.

**Comment by ericthomasswenson** [comment]
Provided on 2/25/2021
