### ISSUE TITLE
Get Diag. Info was not included in Part 1 (but is still buggy in subsequent parts)

### ISSUE THREAD

**Issue by battjt** [battjt/j1939-84#445]
Part 1 Test 10 [Global DM11 (request 59904 for PGN 65235)]

 

    0428.477 500  07    18 EA FF F9 D3 FE 00 (Tx)

    0428.480 500  12    18 E8 FF 2A 00 FF FF FF FF D3 FE 00 

    0428.490 500  12    18 E8 FF 8C 00 00 FF FF FF D3 FE 00 

    0429.099 500  12    18 E8 FF 2A 00 FF FF FF FF D3 FE 00  - Timing Error: Response Time (SA 2A) = 622 ms ( > 220 ms)

    0429.100 000  12    18 E8 FF 8C 00 00 FF FF FF D3 FE 00  - Timing Error: Response Time (SA 8C) = 622 ms ( > 220 ms)

 

**Part 1 Test 10 [Get Diag Info From ECUs]

 

 

Part 1 Test 11 [Global DM21 (request 59904 for PGN 49408 (SPNs 3069, 3294-3296))]**

 

    0436.471 500  07    18 EA FF F9 00 C1 00 (Tx)

    0436.477 000  12    18 C1 FF 00 00 00 00 00 00 00 00 00 (DM21)

    Global DM21 from SA 0 received

 

Part 1 Test 11 [DS DM21 to OBD ECUs]

 

    0438.459 500  07    18 EA 00 F9 00 C1 00 (Tx)

    0438.463 500  12    18 C1 F9 00 00 00 00 00 00 00 00 00 (DM21)

    Direct DM21 Message received from SA 0

**Comment by gumbelmj** [comment]
@battjt what's the action here?  What needs changed?

**Comment by battjt** [comment]
This is a documentation change.

**Comment by ericthomasswenson** [comment]
6.1.10.2.b is not implemented in the source force software and will be deleted, as the individual tests that follow, affirms the reset requirements. Section A-5 will need to be checked.  Future references will rely on this A-5 passage.
“Likewise, when the specification indicates that the test shall verify no diagnostic information was erased, none of the above shall occur.  The occurrence of any of the items above shall be considered an indication of some diagnostic information having been erased.”

6.1.10.2 Fail criteria: 
a. Fail if NACK received from any HD OBD ECU.  
b. Fail if any diagnostic information in any ECU is not reset or starts out with unexpected values.  Diagnostic information is defined in section A.5, Diagnostic Information Definition.15 

(15) Checks for erased data shall at a minimum include those queries provided in the same test part.  Section A.5 provides for all the data that can be checked.

**Comment by ericthomasswenson** [comment]
Delete b in 6.1.10.2 and find a new spot for footnote 15.
_6.1.10.2 Fail criteria:
a. Fail if NACK received from any HD OBD ECU._

b. Fail if any diagnostic information in any ECU is not reset or starts out with unexpected values. Diagnostic information is defined in section A.5, Diagnostic Information Definition.15

**Comment by ericthomasswenson** [comment]
6.1.10.2.b deleted in the 3/10/2021 draft and the foot note can now be found as footnote 43 as shown below.

6.4.13.2	Fail Criteria
a.	Fail if any OBD ECU does not NACK with control byte = 1 or 2 or 3. 
_b._     ECU erases any diagnostic information. See Section A.5 for more information.   _[43]_
_c._    Warn if any OBD ECU NACKs with control byte = 3.

**Comment by ericthomasswenson** [comment]
Provided in March 10, 2021 draft.
