### ISSUE TITLE
Part 1 Step 6 should indicate values need stored

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#458]
Part 1 Step 6 requests DM56 (Model Year and Certification Engine Family).  That information is required in Part2 Step 6.  However Part1 Step6 did not indicate that the information returned from the vehicle needed to be stored.

**Comment by ericthomasswenson** [comment]
Please combine with #461, which was commented upon 1st.

There are backward references in other related parts.
Shall we get together on the 3 cycle countdown where the implanted DTC must be discovered in DM6, and then checked in DM27, DM12, DM1, DM23, DM2, DM28, and the DM25 freeze frame?

Completed test results are also reused to check for erasures.

**Comment by gumbelmj** [comment]
@ericthomasswenson, I'm ok with combining all minor documentation errors into one ticket, but I'm concerned that the issues might be lost in the long list of comments.   Since the final resolution of the issues will fall to you, would you prefer to use one ticket or keep them separate and distinct?

**Comment by ericthomasswenson** [comment]
Proposed text posted in #461

**Comment by gumbelmj** [comment]
Closing this ticket to merge with #461
