### ISSUE TITLE
Part 01 Step 09 should indicate values need stored

### ISSUE THREAD

**Issue by mmschaefer** [battjt/j1939-84#461]
Part 1 Step 9 requests ComponentIdentificationPacket. That information is required in Part2 Step 6. However Part1 Step9 did not indicate that the information returned from the vehicle needed to be stored.

**Comment by ericthomasswenson** [comment]
You’ll likely find several others, shall we start with DM4? CAL ID?
Please respond with a list of all the paragraphs in part 1, where you would prefer a forward reference to reuse.  
This list would make a good footnote someplace around DM4, or perhaps after DM11. or both (divided use)

**Comment by ericthomasswenson** [comment]
Corrected DM4 (old freeze frame) to DM24 in 1st comment.

DM19, DM24, and DM24 are checked using the complete message in part 2.

The counts could change in DM20, thus only the SPNs labels are checked in part 2.  Retrograde motion in numerators and denominators is checked in Part 11.

The enabled status could change, hence there is an emphasis on monitor support in DM26 for part 2.

DM7 requires a constant number of test results using the same SPN and FMI combinations in part 2.  Other parts check for completed results being erased in appropriately by DM22 or DM3

**Comment by ericthomasswenson** [comment]
Corrected DM4 to DM24 ... 

DM19, DM24, DM34, DM56 and Component ID use the complete message from OBD ECUs in Part 2.
A running engine provides no excuse for constant data to change.

DM20 uses the labels in Part 2 as the numerators and denominators could change.  Part 11 checks for retrograde motion. Multiple parts check the ignition counter.

Part 2 checks DM7 for the same number of tests results using the same combinations of SPNs and FMIs.  Other parts check for the erasure of completed tests at inappropriate times, along with all the other OBD data identified in A-5.

Part 2 focuses on Monitor Support for DM26.

**Comment by ericthomasswenson** [comment]
_6.1.3 DM5: Diagnostic readiness 1 **[xx]**_ 

_**[xx] The plurality of part 1 responses are used in part 2 warning and failure criteria. See part 2 criteria for specific details.  OBD ECUs are expected to respond to the same queries when the engine is running, as when the key is on and the engine is off. The data constants in DM24, DM34, DM56 and Component ID are not expected to change, and criteria compare the complete part 1 and part 2 responses. DM20 is checked for changes in monitor identity labels, and DM7 is checked for test results labels. Test criteria is also provided for data that is expected to monotonically increase during the test. Other parts check for inappropriate erasure of test results and other OBD data as discussed in appendix section A-5. Implementation designs shall account for the reuse of earlier responses in later criteria.**_

**Comment by ericthomasswenson** [comment]
Inserted as footnote 4.  Footnote 5 was abridged of duplicative content.

**Comment by ericthomasswenson** [comment]
Provided on 2/25/2021
