### ISSUE TITLE
Part 1 Step 26 Handling changes in SAE Specs

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#475]
`B't PGN 65163 from SA 0 with SPNs 1390   // This is believed to be on request… it clearly was OR`

According to the spec:
65163 - Gaseous Fuel Pressure 1 - GFP1
"100 ms Note: Systems developed to the standard published before May, 2016 might not be transmitted at a 100 ms rate, but be transmitted on request"

How is the tool supposed to know which version of the spec ECU was developed with?

**Comment by ericthomasswenson** [comment]
It’s been 5 years since 2016; let’s enforce the broadcast expectation as the tool will be used starting with 2021MY SI engines.

**Comment by gumbelmj** [comment]
As the tool expects this message to be broadcast, per the current version of the spec, this is closed.
