### ISSUE TITLE
Part 2 Step 10 Reference to Part 1 is wrong

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#485]
6.2.10.2 Fail criteria:
a. Fail if there is any difference in each ECU’s provided test result labels (SPN and FMI combinations) from the test
results received in part 1 test 11, paragraph 6.1.11.31

The Test results were queries in Step 12 of Part 1.

**Comment by ericthomasswenson** [comment]
Correct

**Comment by ericthomasswenson** [comment]
_6.2.10.2 Fail criteria:
a. Fail if there is any difference in each ECU’s provided test result labels (SPN and FMI combinations) from the test results received in part 1 **test 12, paragraph 6.1.12**. [31]_

**Comment by ericthomasswenson** [comment]
Also see section 6, I.  I couldn’t keep it straight so I had to write it down, for everyone.

The  test procedures  for parts  1  through  12  are  written  based  on  the  following  provisions  and conventions.  

I. part 1 through  part  12  procedures are written using an outline format as shown below
A. 6.X        Part X 
B. 6.X.Y     Test  Y  of  Part X
C. 6.X.Y.Z  Step  Z of  Test Y 
The subsection number X  identifies the  part  in the  overall  test  sequence.  The paragraph number Y identifies Test Y  in  Part  X.  And, the subparagraph number Z identifies Step Z within Test Y of Part  X.  An alphabetic enumeration is provided within subparagraphs, this enumeration allows individual criteria, where there is more than one action or failure criterion.

**Comment by ericthomasswenson** [comment]
Text previsously amended to say:
6.2.10.2	Fail Criteria
a.	Fail if there is any difference in each ECU’s provided test result labels (SP and FMI combinations) from the test results received in part 1 test 12, 6.1.12.

**Comment by ericthomasswenson** [comment]
Provided on 2/25/2021
