### ISSUE TITLE
Part 2 Step 11 Reference to Part 1 Step is wrong

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#488]
6.2.11.2 Fail criteria: (if supported)
a. Fail if any OBD ECU that supported DM27 in step 6.1.20 fails to respond.

The part 1 step is actually 21

**Comment by ericthomasswenson** [comment]
Correct. I’ll add it to the list

**Comment by ericthomasswenson** [comment]
_6.2.10.2 Fail criteria: 
a. Fail if there is any difference in each ECU’s provided test result labels (SPN and FMI combinations) from the test results received in part 1 test **12**, paragraph **6.1.12.**_

**Comment by ericthomasswenson** [comment]
Also,

_6.2.16.3 Actions: 
a. DS DM34 to each OBD ECU which responded to the DM34 global request in **part** 1._

**Comment by ericthomasswenson** [comment]
6.2.10.2 corrected to test 12 as shown above.

**Comment by ericthomasswenson** [comment]
Corrected test provided on 2/25/2021
