### ISSUE TITLE
Part 1 Step 21 doesn't indicate the need to save data

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#489]
Part 1 Step 21 data is used in Part 2 Step 11. However, Part 1 Step 21 doesn't indicate when the data received is to be saved.

**Comment by ericthomasswenson** [comment]
Combine with #461. A single list is preferred.

**Comment by ericthomasswenson** [comment]
Proposed text posted in #461

**Comment by gumbelmj** [comment]
Closing this ticket to merge with #461
