### ISSUE TITLE
Part 2 Step 2 should indicate that Not Available is not considered a failure

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#493]

**Comment by ericthomasswenson** [comment]
FAIL: 6.2.2.2.b - An OBD ECU reported active/previously active fault DTCs count not = 0/0
  Reported active fault count = -1
  Reported previously active fault count = -1

is the same behavior as was observed in part 1, 6.1.13.2.
I’m leaning toward, 
    No OBD ECU reported active/previously active fault DTCs count = 0/0 
in both spots
As some secondary OBD ECU, May not support DM2 and will report 0/FF (all faults are 1 trip faults and primary ECU supports DM2/DM23 reporting).  

Indeed, Systems were not required to add support for DM2 where none was provided before as evidenced by if supported in, 6.1.16.2 Fail criteria (if supported):

**Comment by ericthomasswenson** [comment]
Amended text for enhancement TBS.  Amended text for 6.2.2.2 included.

6.1.3 DM5: Diagnostic readiness 1 
6.1.3.1 Actions: 
a. Global4 DM5 (send Request (PGN 59904) for PGN 65230 (SPN 1220)).   
b. Create 'OBD ECU'5 list (comprised of all ECUs that indicate 0x13, 0x14, 0x22, or 0x23 for OBD compliance) for use later in the test as the “OBD ECUs”.  
6.1.3.2 Fail criteria: 
a. Fail if no ECU reports as an OBD ECU. 
b. Fail if any ECU responds with a NACK (for PGN 65230).   
6.1.3.3 Warn criteria: 
a. Warn if more than one ECU responds with a value for OBD compliance where the values are not identical (e.g., if one ECU reports 0x13 and another reports 0x22, if one reports 0x13 and another reports 0x11). 

6.2.2 DM5:  Diagnostic  readiness  1 
6.2.2.1 Actions: 
a. Global  DM5 (send Request  (PGN 59904) for PGN  65230  (SPNs  12181223)). 
b. Display  monitor readiness  composite  value  in  log for OBD ECU replies  only.  
6.2.2.2 Fail/warn criteria: 
a. Fail/warn  per  the section  A.6 Criteria for Readiness  1  Evaluation. 
b. **Fail if no OBD ECU [27] reports active/previously  active fault DTC count =  0/0.** 
c. Warn  if  any  individual  required  monitor,  except  Continuous  Component  Monitoring  (CCM)  is  supported  by  more than  one  OBD  ECU.

**Comment by gumbelmj** [comment]
I thought 6.2.2.2.b would be updated as:
"No OBD ECU reported active/previously active fault DTCs count = 0/0"

**Comment by ericthomasswenson** [comment]
This is now included above for TBS enhancement text.
And explicitly shown for 3.0.0 below.
Sometimes I lose incomplete entries in these dialog boxes.

**Comment by ericthomasswenson** [comment]
The corrected text for 3.0.0 shall reflect

6.2.2 DM5: Diagnostic readiness 1
6.2.2.1 Actions:
a. Global DM5 (send Request (PGN 59904) for PGN 65230 (SPNs 12181223)).
b. Display monitor readiness composite value in log for OBD ECU replies only.
6.2.2.2 Fail/warn criteria:
a. Fail/warn per the section A.6 Criteria for Readiness 1 Evaluation.
b. **Fail if no OBD ECU [27] reports active/previously active fault DTC count = 0/0.**
c. Warn if any individual required monitor, except Continuous Component Monitoring (CCM) is supported by more than one OBD ECU.

**Comment by ericthomasswenson** [comment]
6.2.2.2.b now says:

b.	Fail if no OBD ECU reports active/previously active fault DTC count = 0/0.

**Comment by ericthomasswenson** [comment]
Updated text for 3.0.0 provided on 2/25/2021.  Please create a new issue to track the post release enhancement suggestion.
