### ISSUE TITLE
Part 1 Step 26 - Did we miss a Broadcast PGN?

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#502]
NO.

Specifically looking at SPN 5245 AFT DEF Tank Low Level Indicator

```
Expecting the following messages:
...
BCT PGN 65110 from SA 0 with SPNs 1761, 3031, 5245, 5246
...
```

```
PGN 65110 with Supported SPNs 1761, 3031, 5245, 5246
09:00:31.6383 18FE5600 [8] F9 21 FF FF FF 1F FF FF
Found: AFT 1 DEF Tank 1 Information 1 from Engine #1 (0): 
...
  SPN  5245, AFT DEF Tank Low Level Indicator: 111
...
FAIL: 6.1.26.2.a - SPN 5245 was received as NOT AVAILABLE from Engine #1 (0)
```

Because the SPN is indicated as Supported in the Data Stream by the Engine, but the value was received as N/A, we do a DS request per 6.1.26.5

> 6.1.26.5 Actions3:
> a. DS messages to ECU that indicated support in DM24 for upon request SPNs and SPNs not observed in step 1.

As the SPN was not 'observed' in Step 1.

**Comment by ericthomasswenson** [comment]
Current behavior, checking one more time, is acceptable.  
The undesired behavior is calling FF values a failure, when the SP is not listed in DM24 for data stream support.
Here a listed SP is clearly absent, and the failure message is correct.
