### ISSUE TITLE
Update Section 6.3.2.1

### ISSUE THREAD

**Issue by mmschaefer** [battjt/j1939-84#537]
Update the requirements document to include saving the DM6 data for use later in the testing.  Also, update the reference in 6.3.3.2.a and 6.3.3.3.a to correctly reflect the use of the DM6 data that was gathered and saved during 6.3.2.1

**Comment by ericthomasswenson** [comment]
It’s really a detailed test plan that is intended to be automated. It’s not intended to be either a software top level design or software detailed design for the automation.  It’s more a conceptual work — the background information in sections 4, 5 and 6 would not expected, necessarily, in a software detailed design document (except as needed to document the process requirements of a subsystem or unit). That being said: I’m glad to improve the document with additional, key forward references.

**Comment by ericthomasswenson** [comment]
Here, the following footnote is suggested:

6.3.2 DM6: Emission  related  pending DTCs **_[xx]_**

_**[xx]The DM6 response will contain the Fault A DTC.  This DTC value shall be used to evaluate subsequent DM27 (if supported), DM25, DM12, DM1, DM23, DM2, and DM28 responses, as shown in the Figure 2 signal chart for the tests that provide the timeline axis.  Figure 2 also depicts Fault B and its application to selected DM responses.**_

**Comment by ericthomasswenson** [comment]
Footnote inserted p. 39

**Comment by ericthomasswenson** [comment]
Provided in 2/25/2021 draft
