### ISSUE TITLE
Don't check Broadcast period of DS responses

### ISSUE THREAD

**Issue by gumbelmj** [battjt/j1939-84#563]
Per Email:

> Dear Matt,
> 
> Please enter documentation and enhancement tickets for 6.1.26.6.
> 
> Criteria b. And c. Are not well matched to DS queries, and bely my oral direction to ignore broadcast periods for DS requests.  b. And c. Shall be omitted for the current draft and will be reimagined along with improvements for broadcast on request data. This should match the current implementation.
> 
> There are two use cases. 1. PGs that are broadcast at a regular period upon request. 2. PGs that the manufacturer choose to broadcast to satisfy an information architecture need.  The 1st creates conflicts between part 1 and part 2, when the data continues to be broadcast after engine start.  My recollection is that these use cases are not part of the detailed statement of work.
> 
> 6.1.26.6 Fail/warn criteria3:  [Refer to footnotes 23 and 24 for a and b, respectively] 
> a.  Fail if no response/no valid data for any broadcast SPN indicated as supported by the OBD ECU in DM24.  
> b.  Fail if any parameter in a fixed period broadcast message is not broadcast within ± 10% of the specified broadcast period. 
> c.  Fail if any parameter in a variable period broadcast message exceeds 110% of its recommended broadcast period.26 
> d. Fail/warn if any broadcast data is not valid for KOEO conditions as per section A.1Table A-1, Minimum Data Stream Support. 
> e. Warn/info per Table A-1, if an expected SPN from the DM24 support list is provided by a non-OBD ECU. f. Fail/warn per Table A-1, if two or more ECUs provide an SPN listed in Table A-1.  
> 
> Best Wishes,
> 
> Eric
> 
> Sent from my iPad

**Comment by ericthomasswenson** [comment]
Combine with #525

**Comment by ericthomasswenson** [comment]
Broadcast periods should (again) be checked as part of the enhancement.

Let’s add a heading to better distinguish from the 6.1.26.2 period checks.

**Comment by gumbelmj** [comment]
Closing to merge with #525
